### PR TITLE
Refactor Serial Input Process

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by herjulf** [comment]
Browsed it.
Have no objections but I'll leave it to the WMEA maintainers (Mary, Max, Emmanuel) to merge.
Nice to see you have this collaboration process working. 

BTW did you get some comments on this PR from me before. I did comment for some reason the comments got lost.

**Comment by ghost** [comment]
No, this is the first comment am receiving.

**Comment by herjulf** [comment]
You should ping Max, Mary and Emmanuel who know about maintainers and roadmap.
Possible you can become a collaborator. But you need to keep development in sync.
Keep up with your work.

**Review by mbyamukama — APPROVED** [review]

**Review by mbyamukama — COMMENTED** [review]
Remove the .hex from the .gitignore and send another merge request. Executables are necessary for our remote partners not to recompile.

**Pull request merged**
